/*
 * AdsPLAY.smarttv.js - version 1.7.2 - date: May 25,2017
 */
window.AdsPlaySmartTvJsLoaded||(window.AdsPlaySmartTvJsLoaded=!0,function(l,h){function f(){var f=window.ActiveXObject&&"file:"===location.protocol;if(window.XMLHttpRequest&&!f)return new XMLHttpRequest;try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(k){}window.console&&window.console.error("Your browser doesn't support XML handling!");return null}l.AdsPlayCorsRequest={get:function(h,k,b,a){var d=null,c=function(){if(0==d.readyState||4==d.readyState)if(0==d.status||200<=d.status&&300>d.status||
304==d.status||1223==d.status){for(var c={},p=0;p<b.length;p++){var q=b[p],e=d.getResponseHeader(q);e&&(c[q]=e)}a(c,d.responseText)}else window.console&&window.console.error("Operation failed by AdsPlayRequest.get: "+k)};d||(d=f());d&&(d.open("GET",k,!0),d.onreadystatechange=c,d.withCredentials=h,d.send())}}}("undefined"===typeof window?this:window),function(l,h){function f(){if(!b){b=!0;for(var a=0;a<k.length;a++)k[a].fn.call(window,k[a].ctx);k=[]}}function m(){"complete"===document.readyState&&
f()}h=h||window;var k=[],b=!1,a=!1;h[l||"AdsPlayReady"]=function(d,c){b?setTimeout(function(){d(c)},1):(k.push({fn:d,ctx:c}),"complete"===document.readyState?setTimeout(f,1):a||(document.addEventListener?(document.addEventListener("DOMContentLoaded",f,!1),window.addEventListener("load",f,!1)):(document.attachEvent("onreadystatechange",m),window.attachEvent("onload",f)),a=!0))}}("AdsPlayReady",window),function(l,h){var f=function(f){if("object"!==typeof f.document)throw Error("AdsPlayCookies.js requires a `window` with a `document` object");
var b=function(a,d,c){return 1===arguments.length?b.get(a):b.set(a,d,c)};b._document=f.document;b._cacheKeyPrefix="cookey.";b._maxExpireDate=new Date("Fri, 31 Dec 9999 23:59:59 UTC");b.defaults={path:"/",secure:!1};b.get=function(a){b._cachedDocumentCookie!==b._document.cookie&&b._renewCache();return b._cache[b._cacheKeyPrefix+a]};b.set=function(a,d,c){c=b._getExtendedOptions(c);c.expires=b._getExpiresDate(d===h?-1:c.expires);b._document.cookie=b._generateAdsPlayCookiestring(a,d,c);return b};b.expire=
function(a,d){return b.set(a,h,d)};b._getExtendedOptions=function(a){return{path:a&&a.path||b.defaults.path,domain:a&&a.domain||b.defaults.domain,expires:a&&a.expires||b.defaults.expires,secure:a&&a.secure!==h?a.secure:b.defaults.secure}};b._isValidDate=function(a){return"[object Date]"===Object.prototype.toString.call(a)&&!isNaN(a.getTime())};b._getExpiresDate=function(a,d){d=d||new Date;"number"===typeof a?a=Infinity===a?b._maxExpireDate:new Date(d.getTime()+1E3*a):"string"===typeof a&&(a=new Date(a));
if(a&&!b._isValidDate(a))throw Error("`expires` parameter cannot be converted to a valid Date instance");return a};b._generateAdsPlayCookiestring=function(a,b,c){a=a.replace(/[^#$&+\^`|]/g,encodeURIComponent);a=a.replace(/\(/g,"%28").replace(/\)/g,"%29");b=(b+"").replace(/[^!#$&-+\--:<-\[\]-~]/g,encodeURIComponent);c=c||{};a=a+"="+b+(c.path?";path="+c.path:"");a+=c.domain?";domain="+c.domain:"";a+=c.expires?";expires="+c.expires.toUTCString():"";return a+=c.secure?";secure":""};b._getCacheFromString=
function(a){var d={};a=a?a.split("; "):[];for(var c=0;c<a.length;c++){var n=b._getKeyValuePairFromAdsPlayCookiestring(a[c]);d[b._cacheKeyPrefix+n.key]===h&&(d[b._cacheKeyPrefix+n.key]=n.value)}return d};b._getKeyValuePairFromAdsPlayCookiestring=function(a){var b=a.indexOf("="),b=0>b?a.length:b;return{key:decodeURIComponent(a.substr(0,b)),value:decodeURIComponent(a.substr(b+1))}};b._renewCache=function(){b._cache=b._getCacheFromString(b._document.cookie);b._cachedDocumentCookie=b._document.cookie};
b._areEnabled=function(){var a="1"===b.set("AdsPlayCookies.js",1).get("AdsPlayCookies.js");b.expire("AdsPlayCookies.js");return a};b.enabled=b._areEnabled();return b},m="object"===typeof l.document?f(l):f;"function"===typeof define&&define.amd?define(function(){return m}):"object"===typeof exports?exports.AdsPlayCookies=m:l.AdsPlayCookies=m}("undefined"===typeof window?this:window),function(l,h){function f(c){c=c||{};c.url=c.url||null;c.vars=c.vars||{};c.error=c.error||function(){};c.success=c.success||
function(){};c.vars.cb=Math.floor(1E13*Math.random());var b=[];for(a in c.vars)b.push(encodeURIComponent(a)+"="+encodeURIComponent(c.vars[a]));b=b.join("&");if(c.url){var a=new Image;a.onerror&&(a.onerror=c.error);a.onload&&(a.onload=c.success);a.src=c.noParameter?c.url:c.url+"?"+b}}function m(){var c=(new Date).getTime();return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=(c+16*Math.random())%16|0;c=Math.floor(c/16);return("x"==a?b:b&3|8).toString(16)})}function k(c,a,b,d,
e,g){c.firstChild&&(a='<p id="marquee-'+e+'" style="margin-top:2px; font-size:17px;color:#FFFFFF;animation: marquee 7s linear infinite;white-space: nowrap;" > '+a+(' - <a style="color: #F28807;" onclick="AdsPlay.trackClick('+e+')" href="'+b+'" target="_blank" >'+d+"</a></p>"),b=document.createElement("div"),b.id="div-ad-"+e,b.style.position="absolute",b.style["text-align"]="center",b.style["background-color"]="rgba(7, 7, 7, 0.72)",b.style.width=c.offsetWidth+"px",b.style.top=c.offsetTop+"px",b.style["z-index"]=
"2147483647",b.innerHTML=a,c.insertBefore(b,c.firstChild),f({url:baseUrlTrackingAds,vars:{metric:"impression",adid:e,beacon:adBeacons[e]}}),c=.13*document.getElementById("marquee-"+e).offsetWidth,c="@keyframes marquee  {  0%  { text-indent: -"+c+"px } 100% { text-indent: "+c+"px } }",document.styleSheets&&document.styleSheets.length?document.styleSheets[0].insertRule(c,0):(a=document.createElement("style"),a.innerHTML=c,document.getElementsByTagName("head")[0].appendChild(a)),setTimeout(function(){document.getElementById("div-ad-"+
e).style.display="none"},g))}var b=function(c){var b=(new Date).getTime();var a=0;var d="";var e=document.getElementsByClassName("wrap_desc_content");0<e.length&&(e=e[0].children,2<e.length&&(d=e[1].textContent));for(var e=document.getElementsByTagName("meta"),g=0;g<e.length;g++){var f=e[g];f.getAttribute&&"user"===f.getAttribute("name")&&(a=f.getAttribute("content"));f.getAttribute&&"category"===f.getAttribute("name")&&""===d&&(d=f.getAttribute("content"))}e=AdsPlayCookies.get("apluuid");e||(e=m(),
AdsPlayCookies.set("apluuid",e,{expires:315569520}));e="uuid="+e;for(g=0;g<c.length;g++)e+="&placement="+c[g];e+="&referrer="+encodeURIComponent(document.referrer?document.referrer:"");c=e+="&url="+encodeURIComponent(document.location.href);e=encodeURIComponent;g=document.title;0<location.href.indexOf("smarttv.fptplay")&&(g=AdsPlayCookies.get("aplcxt"));e=c+("&cxt="+e(g));e+="&cxkw="+encodeURIComponent(d);e+="&ut="+encodeURIComponent(a);c="d3";a=b%3;1===a?c="d1":2===a&&(c="d2");return document.location.protocol+
"//"+c+".adsplay.net/delivery/zone/?"+(e+("&t="+b))},a=function(c){var a=c.adMedia,b=c.clickthroughUrl,d=c.clickActionText,e=c.adId,f=c.adBeacon,h=c.autoHideTimeout;if(c=document.getElementById(c.videoPlayerId))adBeacons[e]=f,k(c,a,b,d,e,h)},d=function(c){c=c.tracking3rdUrls;if("object"===typeof c)for(var a=0;a<c.length;a++){var b=c[a];b&&setTimeout(function(a){f({url:a,vars:{}})},1E3*b.delay,b.url)}};l.AdsPlay={getVastUrl:function(a,d){var c=[];c.push(d);return b(c)+"&at=tvc"},loadOverlayAds:function(c){c=
b(c)+"&at=overlay";AdsPlayCorsRequest.get(!1,c,[],function(c,b){for(var f=JSON.parse(b),e=0;e<f.length;e++){var g=f[e],h=g.timeToShow;4===g.adType?setTimeout(a,h,g):10===g.adType&&d(g)}window.console&&window.console.log(f)})}}}("undefined"===typeof window?this:window),AdsPlayReady(function(){window.console&&window.console.log("AdsPlayReady ...");setTimeout(function(){AdsPlay.loadOverlayAds([446])},3E3)}));