package uspa.cdp.model;

//class Event(db.Entity):
//    id = PrimaryKey(str, 36)
//    created_at = Required(datetime, index='event_time_idx')
//    session_key = Required(str, 32, index='event_session_key_idx')
//    tracker_id = Required(str, 32, index='event_tracker_idx')
//    collection_id = Required(str, 32, index='event_collection_idx')
//    metric_name = Required(str, 42, index='event_metric_name_idx')
//    metric_value = Required(int, size=64, default=1)
//    ref_profile_id = Required(str, 32, index='event_profile_idx')
//    ref_profile_type = Optional(int, size=8, default=0, unsigned=True)
//    src_touchpoint_id = Required(str, 32, index='event_src_ctx_idx')
//    ref_touchpoint_id = Optional(str, 32, index='event_ref_ctx_idx')
//    ref_channel_id = Optional(str, 32, index='event_channel_idx')
//    ref_campaign_id = Optional(str, 32, index='event_campaign_idx')
//    ref_post_id = Optional(str, 32, index='event_post_idx')
//    ref_message_id = Optional(str, 32, index='event_message_idx')
//    ref_service_id = Optional(str, 32, index='event_service_idx')
//    ref_item_id = Optional(str, 32, index='event_product_idx')
//    ref_survey_id = Optional(str, 32, index='event_survey_idx')
//    ref_journey_id = Optional(str, 32)
//    ref_journey_stage = Optional(int, size=8, unsigned=True)
//    time_spent = Optional(int, size=32, default=0, unsigned=True)
//    browser_name = Optional(str, 100)
//    web_cookies = Optional(str, 1000)
//    device_id = Optional(str, 36, index='event_device_idx')
//    device_os = Optional(str, 100)
//    device_name = Optional(str, 100)
//    source_ip = Optional(str, 40, index='event_ip_idx')
//    feedback_data = Optional(str, 1000)
//    partition_id = Optional(int, size=16, default=1)
public class TrackingEvent {

}
