/*
 * AdsPLAY.js for iTVAd - version 1.1.6 - date:22/06/2016
 */
if(!window.AdsPlayReady&&(function(e,f){function g(){var e=window.ActiveXObject&&"file:"===location.protocol;if(window.XMLHttpRequest&&!e)return new XMLHttpRequest;try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(n){}window.console&&window.console.error("Your browser doesn't support XML handling!");return null}e.AdsPlayCorsRequest={get:function(e,n,a,b){var c=null,d=function(){if(0==c.readyState||4==c.readyState)if(0==c.status||200<=c.status&&300>c.status||304==c.status||1223==c.status){for(var d=
{},e=0;e<a.length;e++){var g=a[e],f=c.getResponseHeader(g);f&&(d[g]=f)}b(d,c.responseText)}else window.console&&window.console.error("Operation failed by AdsPlayRequest.get: "+n)};c||(c=g());c&&(c.open("GET",n,!0),c.onreadystatechange=d,c.withCredentials=e,c.send())}}}("undefined"===typeof window?this:window),function(e,f){function g(){if(!a){a=!0;for(var b=0;b<n.length;b++)n[b].fn.call(window,n[b].ctx);n=[]}}function p(){"complete"===document.readyState&&g()}f=f||window;var n=[],a=!1,b=!1;f[e||"AdsPlayReady"]=
function(c,d){a?setTimeout(function(){c(d)},1):(n.push({fn:c,ctx:d}),"complete"===document.readyState?setTimeout(g,1):b||(document.addEventListener?(document.addEventListener("DOMContentLoaded",g,!1),window.addEventListener("load",g,!1)):(document.attachEvent("onreadystatechange",p),window.attachEvent("onload",g)),b=!0))}}("AdsPlayReady",window),function(e,f){var g=function(e){if("object"!==typeof e.document)throw Error("AdsPlayCookies.js requires a `window` with a `document` object");var a=function(b,
c,d){return 1===arguments.length?a.get(b):a.set(b,c,d)};a._document=e.document;a._cacheKeyPrefix="cookey.";a._maxExpireDate=new Date("Fri, 31 Dec 9999 23:59:59 UTC");a.defaults={path:"/",secure:!1};a.get=function(b){a._cachedDocumentCookie!==a._document.cookie&&a._renewCache();return a._cache[a._cacheKeyPrefix+b]};a.set=function(b,c,d){d=a._getExtendedOptions(d);d.expires=a._getExpiresDate(c===f?-1:d.expires);a._document.cookie=a._generateAdsPlayCookiestring(b,c,d);return a};a.expire=function(b,c){return a.set(b,
f,c)};a._getExtendedOptions=function(b){return{path:b&&b.path||a.defaults.path,domain:b&&b.domain||a.defaults.domain,expires:b&&b.expires||a.defaults.expires,secure:b&&b.secure!==f?b.secure:a.defaults.secure}};a._isValidDate=function(b){return"[object Date]"===Object.prototype.toString.call(b)&&!isNaN(b.getTime())};a._getExpiresDate=function(b,c){c=c||new Date;"number"===typeof b?b=Infinity===b?a._maxExpireDate:new Date(c.getTime()+1E3*b):"string"===typeof b&&(b=new Date(b));if(b&&!a._isValidDate(b))throw Error("`expires` parameter cannot be converted to a valid Date instance");
return b};a._generateAdsPlayCookiestring=function(b,a,d){b=b.replace(/[^#$&+\^`|]/g,encodeURIComponent);b=b.replace(/\(/g,"%28").replace(/\)/g,"%29");a=(a+"").replace(/[^!#$&-+\--:<-\[\]-~]/g,encodeURIComponent);d=d||{};b=b+"="+a+(d.path?";path="+d.path:"");b+=d.domain?";domain="+d.domain:"";b+=d.expires?";expires="+d.expires.toUTCString():"";return b+=d.secure?";secure":""};a._getCacheFromString=function(b){var c={};b=b?b.split("; "):[];for(var d=0;d<b.length;d++){var e=a._getKeyValuePairFromAdsPlayCookiestring(b[d]);
c[a._cacheKeyPrefix+e.key]===f&&(c[a._cacheKeyPrefix+e.key]=e.value)}return c};a._getKeyValuePairFromAdsPlayCookiestring=function(b){var a=b.indexOf("="),a=0>a?b.length:a;return{key:decodeURIComponent(b.substr(0,a)),value:decodeURIComponent(b.substr(a+1))}};a._renewCache=function(){a._cache=a._getCacheFromString(a._document.cookie);a._cachedDocumentCookie=a._document.cookie};a._areEnabled=function(){var b="1"===a.set("AdsPlayCookies.js",1).get("AdsPlayCookies.js");a.expire("AdsPlayCookies.js");return b};
a.enabled=a._areEnabled();return a},p="object"===typeof e.document?g(e):g;"function"===typeof define&&define.amd?define(function(){return p}):"object"===typeof exports?exports.AdsPlayCookies=p:e.AdsPlayCookies=p}("undefined"===typeof window?this:window),function(e,f){function g(h){h=h||{};h.url=h.url||null;h.vars=h.vars||{};h.error=h.error||function(){};h.success=h.success||function(){};h.vars.cb=Math.floor(1E13*Math.random());var b=[],a;for(a in h.vars)b.push(encodeURIComponent(a)+"="+encodeURIComponent(h.vars[a]));
b=b.join("&");h.url&&(a=new Image,a.onerror&&(a.onerror=h.error),a.onload&&(a.onload=h.success),a.src=h.url+"?"+b)}function p(){var h=(new Date).getTime();return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=(h+16*Math.random())%16|0;h=Math.floor(h/16);return("x"==a?b:b&3|8).toString(16)})}function n(){var a=AdsPlayCookies.get("aplloc");if("string"!==typeof a){var b="https://static.fptplay.net/zone.html?time"+(new Date).getTime();AdsPlayCorsRequest.get(!1,b,["x-zone","content-type"],
function(b,c){a="vn-"+b["x-zone"];AdsPlayCookies.set("aplloc",a,{expires:604800})});a=""}return a}function a(a,b,c,e,d,k){a.firstChild&&(b='<p id="marquee-'+d+'" style="margin-top:2px; font-size:17px;color:#FFFFFF;animation: marquee 7s linear infinite;white-space: nowrap;" > '+b+(' - <a style="color: #F28807;" onclick="AdsPlay.trackClick('+d+')" href="'+c+'" target="_blank" >'+e+"</a></p>"),c=document.createElement("div"),c.id="div-ad-"+d,c.style.position="absolute",c.style["text-align"]="center",
c.style["background-color"]="rgba(7, 7, 7, 0.72)",c.style.width=a.offsetWidth+"px",c.style.top=a.offsetTop+"px",c.style["z-index"]="2147483647",c.innerHTML=b,a.insertBefore(c,a.firstChild),g({url:r,vars:{metric:"impression",adid:d,beacon:q[d]}}),a=.13*document.getElementById("marquee-"+d).offsetWidth,a="@keyframes marquee  {  0%  { text-indent: -"+a+"px } 100% { text-indent: "+a+"px } }",document.styleSheets&&document.styleSheets.length?document.styleSheets[0].insertRule(a,0):(b=document.createElement("style"),
b.innerHTML=a,document.getElementsByTagName("head")[0].appendChild(b)),setTimeout(function(){document.getElementById("div-ad-"+d).style.display="none"},k))}function b(a,b,c,d,e,k,l,m){c.firstChild&&(a='<a onclick="AdsPlay.trackClick('+l+')" href="'+e+'" title="'+k+'" target="_blank" >'+('<img style="width:'+a+"px;height:"+b+'px" src="'+d+'" />')+"</a>",b=document.createElement("div"),b.id="div-ad-"+l,b.style.position="absolute",b.style["text-align"]="center",b.style["background-color"]="rgba(221, 221, 221, 0)",
b.style.width=c.offsetWidth+"px",b.style.top=c.offsetTop+c.offsetHeight-130+"px",b.style["z-index"]="2147483647",b.innerHTML=a,c.insertBefore(b,c.firstChild),g({url:r,vars:{metric:"impression",adid:l,beacon:q[l]}}),setTimeout(function(){document.getElementById("div-ad-"+l).style.display="none"},m))}var c=function(a,b){var c,d,e=(new Date).getTime();c=0;d="";for(var k=document.getElementsByTagName("meta"),l=0;l<k.length;l++){var m=k[l];m.getAttribute&&"user"===m.getAttribute("name")&&(c=m.getAttribute("content"));
m.getAttribute&&"category"===m.getAttribute("name")&&""===d&&(d=m.getAttribute("content"))}d=d.substr(0,100);k=AdsPlayCookies.get("apluuid");k||(k=p(),AdsPlayCookies.set("apluuid",k,{expires:315569520}));k="uuid="+k;for(l=0;l<b.length;l++)k+="&placement="+b[l];k+="&referrer="+encodeURIComponent(document.referrer?document.referrer:"");k+="&url="+encodeURIComponent(document.location.href);l=encodeURIComponent;(m=document.getElementById("livetv_title"))||(m=document.getElementById("vod_url"));m=m?m.innerHTML:
document.title;m=m.substr(0,100);k+="&cxt="+l(m);k+="&cxkw="+encodeURIComponent(d);k+="&ut="+encodeURIComponent(c);k+="&loc="+encodeURIComponent(n());c="d3";d=e%6;1===d?c="d1":2===d?c="d2":4===d&&(c="d4");return document.location.protocol+"//"+c+".adsplay.net/delivery/zone/"+a+"?"+(k+("&t="+e))},d={getVastUrl:function(a,b){var d=[];d.push(b);return c(a,d)+"&at=tvc"},trackClick:function(a){document.getElementById("div-ad-"+a).style.display="none";g({url:r,vars:{metric:"click",adid:a,beacon:q[a]}});
return!0}},r=document.location.protocol+"//log.adsplay.net/track/ads",q={},t=function(b){var c=b.adMedia,d=b.clickthroughUrl,e=b.clickActionText,g=b.adId,k=b.adBeacon,l=b.autoHideTimeout;if(b=document.getElementById(b.videoPlayerId))q[g]=k,a(b,c,d,e,g,l)},u=function(a){var c=a.width,d=a.height,e=a.adMedia,g=a.clickthroughUrl,k=a.clickActionText,l=a.adId,m=a.adBeacon,f=a.autoHideTimeout;if(a=document.getElementById(a.videoPlayerId))q[l]=m,b(c,d,a,e,g,k,l,f)};d.loadOverlayAds=function(a,b,d){a=c(a,
b)+"&at=overlay";AdsPlayCorsRequest.get(!1,a,[],function(a,b){for(var c=JSON.parse(b),d=0;d<c.length;d++){var e=c[d],g=e.timeToShow,f=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(f=parseFloat(RegExp.$1));if(f=-1==f){var f=!1,h=navigator.userAgent||navigator.vendor||window.opera;if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test(h)||
/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(h.substr(0,
4)))f=!0;f=!f}f&&(4===e.adType?setTimeout(t,g,e):3===e.adType&&setTimeout(u,g,e));5===e.adType&&(g="aplpm"+e.placementId,f='<a target="_blank" href="'+e.clickthroughUrl+'" title="'+e.clickActionText+'">',f+='<img src="'+e.adMedia+'" width="'+e.width+'" height="'+e.height+'" alt="" border="0/"></a>',document.getElementById(g).innerHTML=f)}window.console&&window.console.log(c)})};e.AdsPlay=d}("undefined"===typeof window?this:window),AdsPlayReady(function(){0<location.href.indexOf("//fptplay.net")&&
(window.console&&window.console.log("AdsPlayReady ..."),setTimeout(function(){for(var e=[401,501],f=document.getElementsByClassName("adsplay-placement"),g={},p=0;p<f.length;p++){var n=f[p];e.push(n.getAttribute("data-placement-id"));g[n.getAttribute("id")]=n}AdsPlay.loadOverlayAds(1001,e,g)},5E3))}),0<location.href.indexOf("//fptplay.net"))){var _urq=_urq||[];_urq.push(["initSite","77d087a8-b93c-4f3b-aa2e-b0cfb1f0b7ad"]);(function(){var e=document.createElement("script");e.type="text/javascript";
e.async=!0;e.src="https:"==document.location.protocol?"https://st.adsplay.net/js/userreport.js":"http://st.adsplay.net/js/userreport.js";var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(e,f)})()};
